### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by gtaylor44** [antoniocorreia/Tesseract.NETCore#1]
Could you please set the properties of these files to "Copy Always"?

"lib\x64\liblept1742.dll"
"lib\x64\libtesseract3051.dll"
"lib\x64\tesseract.exe"
"lib\x86\tesseract.exe"

They're missing after clone.

**Comment by antoniocorreia** [comment]
sorry, just added them

**Comment by gtaylor44** [comment]
Thanks
